#!/usr/bin/env python
# encoding: utf-8

# (c) Wiltrud Kessler, 22.12.17

"""
>python -u "extractFilesFromIliasDownload.py" ~/Downloads/test2/1513940796__0__fold_1809320
/home/wiltrud/MINT/LPropInf1/Abgaben/1524580690__0__fold_1809320

"""

import os, sys
from shutil import copyfile
import re


destFolder = "/home/wiltrud/Downloads/PropInf/"
totalFiles = 0


def extractFile(parent, folder):
   """
   Expected format below 'folder':
      - 1513940794__0__file_1821716
         - Modules
            - File
               - set_1
                  - expDir_1
                     - <ACTUAL FILE>
                  export.xml
         - Services
            - MetaData
               - set_1
                  export.xml
         manifest.xml

   export.xml from SERVICES
   <?xml version="1.0" encoding="utf-8"?><!--Generated by ILIAS XmlWriter--><exp:Export InstallationId="0" InstallationUrl="https://ilias3.uni-stuttgart.de" Entity="md" SchemaVersion="4.1.0" TargetRelease="5.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" xsi:schemaLocation="http://www.ilias.de/Services/Export/exp/4_1 https://ilias3.uni-stuttgart.de/xml/ilias_export_4_1.xsd http://www.ilias.de/Services/MetaData/md/4_1 https://ilias3.uni-stuttgart.de/xml/ilias_md_4_1.xsd" xmlns="http://www.ilias.de/Services/MetaData/md/4_1"><exp:ExportItem Id="1821716:0:file"><MetaData><General Structure="Hierarchical"><Identifier Catalog="ILIAS" Entry="il_0_file_1821716"/><Title Language="de">Quadgleichung.java</Title><Language Language="de"/><Description Language="de"></Description><Keyword Language="de"/></General><Technical><Format>text/plain</Format><Size>496</Size></Technical></MetaData></exp:ExportItem></exp:Export>

   export.xml from FILE
   <?xml version="1.0" encoding="utf-8"?><!--Generated by ILIAS XmlWriter--><exp:Export InstallationId="0" InstallationUrl="https://ilias3.uni-stuttgart.de" Entity="file" SchemaVersion="4.1.0" TargetRelease="5.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" xsi:schemaLocation="http://www.ilias.de/Services/Export/exp/4_1 https://ilias3.uni-stuttgart.de/xml/ilias_export_4_1.xsd http://www.ilias.de/Modules/File/file/4_1 https://ilias3.uni-stuttgart.de/xml/ilias_file_4_1.xsd" xmlns="http://www.ilias.de/Modules/File/file/4_1"><exp:ExportItem Id="1821716"><File obj_id="il_0_file_1821716" version="1" size="496" type="text/plain"><Filename>Quadgleichung.java</Filename><Title>Quadgleichung.java</Title><Description></Description><Rating>0</Rating><Content mode="COPY">Modules/File/set_1/expDir_1/Quadgleichung.java</Content><Versions><Version id="1" date="1513849340" usr_id="il_0_usr_1643847"/></Versions></File></exp:ExportItem></exp:Export>
   """
   path = parent + "/" + folder
   myfolder = os.listdir(path)[0]
   path = path + "/" + myfolder


   try:
      exportXml = path + "/Modules/File/set_1/export.xml"
      p = re.compile('usr_id="([^"]*)')
      username = ""
      for line in open(exportXml, 'r'):
         m = p.search(line)
         if m:
            username =  m.group(1)
         else:
            print "ERROR no username found"
   except Exception as e:
      print e

   try:
      thefilefolder = path + "/Modules/File/set_1/expDir_1"
      dst = destFolder + "/" + username + "/"
      if not os.path.exists(dst):
         os.makedirs(dst)
      for file in os.listdir(thefilefolder):
         global totalFiles
         print("Copying %s to %s " % (file, dst))
         if os.path.exists(dst + file):
            copyfile(thefilefolder + "/" + file,  dst + file + "_____" + str(totalFiles))
         else:
            copyfile(thefilefolder + "/" + file,  dst + file)
         totalFiles = totalFiles + 1

   except Exception as e:
      print e




#### MAIN ####

print "Muss noch aufgeraeumt werden!!!"

if len(sys.argv)<1:
   print "Usage: python extractFilesFromIliasDownload.py iliasFolder"
   sys.exit(1)

iliasFolder = sys.argv[1]



# -- start --

for file in os.listdir(iliasFolder):

   if os.path.isdir(iliasFolder + "/" + file):
      print("Processing folder: %s"  % (file))
      extractFile(iliasFolder, file)

   else:
      print("Ignoring file: %s"  % (file))



print "\ndone!"
